#---------------------------
# Material-T
# Author: Rook1e
# Github: https://github.com/0x2e/Material-T
#---------------------------


#---------------------------
# 全局
# Site
#---------------------------
favicon: /img/favicon.png
apple_touch_icon: /img/apple-touch-icon.png
title_join_string: ' ~ '  # 浏览器标签页中的标题分隔符，效果： 文章名 ~ 站点名
highlight:
  enable: true
  theme: tomorrow-night-eighties # available: github-v2 | tomorrow | tomorrow-night | tomorrow-night-eighties，更多主题可从 https://jmblog.github.io/color-themes-for-google-code-prettify/ 获取，保存为 `*.min.css` 到 `source/lib/prettify/`，在其中 .prettyprint{ background: ***; ...} 的background 值后加上 !important，例如：.prettyprint{background:#fafbfc!important; ...}
fun_features:
  typing: # 为 subtitle 添加打字机效果
    enable: true
    typeSpeed: 70 # 打印速度
    cursorChar: "_" # 游标字符
    loop: false # 是否循环播放效果
  anchorjs: # 为文章内容中的标题添加锚图标
    enable: true
    element: h1,h2,h3,h4,h5,h6
    placement: right # icon放置的位置： left | right
    visible: false # true：一直可见，false：鼠标悬停时出现
    icon: "" # 例如：§ | # | ❡ 等，留空则为默认效果
baidu_analytics:  # 百度统计的Key
google_analytics:

#---------------------------
# 导航栏
# Head Navbar
#---------------------------
navbar:
  menu:
    Home: /
    Archives: /archives/
    About: /about/
  blog_title:  # 导航栏左侧的标题，为空则按 hexo config.title 显示

#---------------------------
# 页脚
# Footer
#---------------------------
footer:
  beian:  # The footer of China's website policy, other areas keep disable
    enable: false
    icp_text: 京ICP证123456号 # ICP证号
    police_text: 京公网安备12345678号 # 公安备案号，不填则只显示ICP
    police_code: 12345678 # 公安备案的编号，用于URL跳转查询


#---------------------------
# 首页
# Index Page
#---------------------------
index:
  banner_img: /img/index.jpg
  banner_img_height: 100  # available: 0 - 100
  slogan:  # 首页副标题的独立设置
    enable: true  # 为 false 则不显示任何内容
    text:  # 为空则按 hexo config.subtitle 显示
  auto_excerpt:
    enable: true
  post_url_target: _self  # available: _blank | _self
  post_info:
    enable: true


#---------------------------
# 文章页
# Post Page
#---------------------------
post: 
  banner_img: /img/post.jpg
  banner_img_height: 70  # available: 0 - 100
  date_format: "dddd, MMMM Do YYYY, h:mm a"
  toc: 
    enable: true
  copyright:
    enable: true
    content: '本博客所有文章除特别声明外，均采用 <a href="https://zh.wikipedia.org/wiki/Wikipedia:CC_BY-SA_3.0%E5%8D%8F%E8%AE%AE%E6%96%87%E6%9C%AC" rel="nofollow noopener">CC BY-SA 3.0协议</a> 。转载请注明出处！'
  custom:
    enable: false
    content: '<img src="https://octodex.github.com/images/jetpacktocat.png" class="rounded mx-auto d-block mt-5" style="width:150px; height:150px;">' # 自定义区域，支持 HTML，可自行插入赞赏码、公众号二维码等内容
  comments: 
    enable: false
    type: disqus  # available: disqus | valine

# Disqus
disqus:
  shortname: # your shortname

# Valine
# You can get your appid and appkey from https://leancloud.cn
# More info available at https://valine.js.org
valine:
  enable: false # When enable is set to be true, leancloud_visitors is recommended to be closed for the re-initialization problem within different leancloud adk version.
  appid:  # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier, See: https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: 说点什么 # comment box placeholder
  avatar: retro # gravatar style https://valine.js.org/avatar.html
  pageSize: 10 # pagination size
  visitor: false # leancloud-counter-security is not supported for now. When visitor is set to be true, appid and appkey are recommended to be the same as leancloud_visitors' for counter compatibility. Article reading statistic https://valine.js.org/visitor.html


#---------------------------
# 归档页
# Archive Page
#---------------------------
archive:
  banner_img: /img/archive.jpg
  banner_img_height: 80  # available: 0 - 100


#---------------------------
# 关于页
# About Page
#---------------------------
about:  # 以下仅为页面顶部的基本信息，更多内容请在 /Material-T/about.md 中编辑，支持 markdown 和 HTML
  banner_img: /img/about.jpg
  banner_img_height: 80  # available: 0 - 100
  avatar: /img/avatar.png # 头像
  name: myname
  introduce: info / info / info # 支持 HTML
  icons: # 更多图标可从 https://fontawesome.com/icons 查找，并以 "图标名: url" 的格式添加在下方
    "fab fa-github": https://github.com
    "fab fa-twitter": https://twitter.com


#---------------------------
# 404页
# 404 Page
#---------------------------
page404:
  banner_img: /img/index.jpg
  banner_img_height: 80  # available: 0 - 100
  subtitle: 'Page not found'